FashoinPoint/Areas/Admin/Controllers/NewDropsController.cs
using Fashion.Application.Common;
using Fashion.Application.Interfaces;
using Fashion.Domin.ApplicationEnums;
using Fashion.Domin.Model;
using Fashion.Domin.ViewModel;
using Fashion.Infrastructure.Repositorys;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FashoinPoint.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewDropsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public NewDropsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<NewDrops> newDrops = await _unitOfWork.NewDrops.GetAllNewDrops();

            return View(newDrops);

        }

        [HttpGet]
        public IActionResult Create()
        {

            IEnumerable<SelectListItem> brandList = _unitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> clothesList = _unitOfWork.Clothes.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> sizesList = Enum.GetValues(typeof(Sizes))
                .Cast<Sizes>()
                .Select(x => new SelectListItem
                {
                    Text = x.ToString().ToUpper(),
                    Value = ((int)x).ToString()
                });

         
            NewDropVM newDropsVM = new NewDropVM
            {
                NewDrops = new NewDrops(),
                BrandList = brandList,
                ClothesList = clothesList,
                SizesList = sizesList

            };

            return View(newDropsVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewDropVM newDropsVM)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();

                var upload = Path.Combine(webRootPath, @"images\newDrops");

                var extension = Path.GetExtension(file[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extension), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                newDropsVM.NewDrops.ClotheImage = @"\images\newDrops\" + newFileName + extension;
            }


            if (ModelState.IsValid)
            {
                await _unitOfWork.NewDrops.Create(newDropsVM.NewDrops);
                await _unitOfWork.SaveAsync();

                TempData["success"] = CommonMessages.RecordCreated;

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            NewDrops newDrops = await _unitOfWork.NewDrops.GetNewDropsById(id);
            return View(newDrops);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            NewDrops newDrops = await _unitOfWork.NewDrops.GetNewDropsById(id);

            IEnumerable<SelectListItem> brandList = _unitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> ClothesList = _unitOfWork.Clothes.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> sizesList = Enum.GetValues(typeof(Sizes))
                .Cast<Sizes>()
                .Select(x => new SelectListItem
                {
                    Text = x.ToString().ToUpper(),
                    Value = ((int)x).ToString()
                });

          
            NewDropVM newDropsVM = new NewDropVM
            {
                NewDrops = newDrops,
                BrandList = brandList,
                ClothesList = ClothesList,
                SizesList = sizesList

            };

            return View(newDropsVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(NewDropVM newDropVM)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if (file.Count > 0)
            {
                string newFileName = Guid.NewGuid().ToString();

                var upload = Path.Combine(webRootPath, @"images\newDrops");

                var extension = Path.GetExtension(file[0].FileName);

                /// delete old image

                var objFromDb = await _unitOfWork.NewDrops.GetByIdAsync(newDropVM.NewDrops.Id);

                if (objFromDb != null)
                {
                    var oldImagePath = Path.Combine(webRootPath, objFromDb.ClotheImage.Trim('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                }

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extension), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }
                newDropVM.NewDrops.ClotheImage = @"\images\newDrops\" + newFileName + extension;
            }


            if (ModelState.IsValid)
            {
                await _unitOfWork.NewDrops.Update(newDropVM.NewDrops);
                await _unitOfWork.SaveAsync();

                TempData["warning"] = CommonMessages.RecordUpdated;

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            NewDrops newDrops = await _unitOfWork.NewDrops.GetByIdAsync(id);

            IEnumerable<SelectListItem> brandList = _unitOfWork.Brand.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> clothesList = _unitOfWork.Clothes.Query().Select(x => new SelectListItem
            {
                Text = x.Name.ToUpper(),
                Value = x.Id.ToString()
            });

            IEnumerable<SelectListItem> sizesList = Enum.GetValues(typeof(Sizes))
                .Cast<Sizes>()
                .Select(x => new SelectListItem
                {
                    Text = x.ToString().ToUpper(),
                    Value = ((int)x).ToString()
                });

            NewDropVM newDropsVM = new NewDropVM
            {
                NewDrops = newDrops,
                BrandList = brandList,
                ClothesList = clothesList,
                SizesList = sizesList
              
            };

            return View(newDropsVM);


        }
        [HttpPost]
        public async Task<IActionResult> Delete(NewDropVM newDropsVM)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            if (!string.IsNullOrEmpty(newDropsVM.NewDrops.ClotheImage))
            {
                /// delete old image

                var objFromDb = await _unitOfWork.NewDrops.GetByIdAsync(newDropsVM.NewDrops.Id);

                if (objFromDb != null)
                {
                    var oldImagePath = Path.Combine(webRootPath, objFromDb.ClotheImage.Trim('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                }

            }
            await _unitOfWork.NewDrops.Delete(newDropsVM.NewDrops);
            await _unitOfWork.SaveAsync();

            TempData["error"] = CommonMessages.RecordDeleted;

            return RedirectToAction(nameof(Index));
        }

    }
}

FashoinPoint/Areas/Admin/Views/NewDrops/Create.cshtml
@model NewDropVM

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Create NewDrops</h2>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-12 border-1 border p-4">
            <form method="post" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClotheName" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.ClotheName" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.ClotheName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.BrandId" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.BrandId" asp-items="@Model.BrandList" class="form-select"></select>
                            <option disabled selected>-----select Brand---</option>
                            <span asp-validation-for="@Model.NewDrops.BrandId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClothesID" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.ClothesID" asp-items="@Model.ClothesList" class="form-select"></select>
                            <option disabled selected>-----select Category---</option>
                            <span asp-validation-for="@Model.NewDrops.ClothesID" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Sizes" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.Sizes" asp-items="@Model.SizesList" class="form-select"></select>

                            <span asp-validation-for="@Model.NewDrops.Sizes" class="text-danger"></span>
                        </div>
                    </div>

                  
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Price" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Price" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.Price" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Quantities" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Quantities" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.Quantities" class="text-danger"></span>
                        </div>
                    </div>

                  
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClotheImage" class="form-label"></label>
                            <input type="file" name="files" id="uploadBox" class="form-control" />

                        </div>
                    </div>

                    <div class="mb-3">
                        <a asp-area="Admin" asp-controller="NewDrops" asp-action="Index" class="btn btn-danger">Back</a>
                        <button type="submit" class="btn btn-success">Create</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_validationScriptsPartial" />
}

FashoinPoint/Areas/Admin/Views/NewDrops/Delete.cshtml
@model NewDropVM

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Delete NewDrops</h2>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-8 border-1 border p-4">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.NewDrops.Id" hidden />
                <input asp-for="@Model.NewDrops.ClotheImage" hidden />
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClotheName" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.ClotheName" class="form-control" disabled />
                            <span asp-validation-for="@Model.NewDrops.ClotheName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.BrandId" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.BrandId" asp-items="@Model.BrandList" class="form-select" disabled></select>
                            <option disabled selected>-----select Brand---</option>
                            <span asp-validation-for="@Model.NewDrops.BrandId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClothesID" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.ClothesID" asp-items="@Model.ClothesList" class="form-select" disabled></select>
                            <option disabled selected>-----select Category---</option>
                            <span asp-validation-for="@Model.NewDrops.ClothesID" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Sizes" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.Sizes" asp-items="@Model.SizesList" class="form-select" disabled></select>

                            <span asp-validation-for="@Model.NewDrops.Sizes" class="text-danger"></span>
                        </div>
                    </div>

                  

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Price" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Price" class="form-control" disabled />
                            <span asp-validation-for="@Model.NewDrops.Price" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Quantities" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Quantities" class="form-control" disabled />
                            <span asp-validation-for="@Model.NewDrops.Quantities" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="mb-3">
                        <a asp-area="Admin" asp-controller="NewDrops" asp-action="Index" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>

            </form>
        </div>

    </div>
</div>

@section Scripts {
    <partial name="_validationScriptsPartial" />
}

FashoinPoint/Areas/Admin/Views/NewDrops/Details.cshtml
@using Fashion.Domin.ApplicationEnums

@model NewDrops

<div class="container">
    <div class="card">
        <div class="card-header text-center text-uppercase">
            Demo Details
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Id</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Id</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Name</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.ClotheName</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Brand</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Brand.Name</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Clothes</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Clothes.Name</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Sizes</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @((Sizes)Model.Sizes)</p>
                        </div>
                    </div>

                  

                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Price</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Price</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong> Quantities</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text">: @Model.Quantities</p>
                        </div>
                    </div>


                </div>

                <div class="col-md-4">
                    <img src="@Model.ClotheImage" width="100%" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <a asp-area="Admin" asp-controller="NewDrops" asp-action="Index" class="btn btn-danger">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

FashoinPoint/Areas/Admin/Views/NewDrops/Edit.cshtml
@model NewDropVM

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Update NewDrops</h2>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-8 border-1 border p-4">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.NewDrops.Id" hidden />
                <div class="row">
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClotheName" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.ClotheName" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.ClotheName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.BrandId" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.BrandId" asp-items="@Model.BrandList" class="form-select"></select>
                            <option disabled selected>-----select Brand---</option>
                            <span asp-validation-for="@Model.NewDrops.BrandId" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClothesID" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.ClothesID" asp-items="@Model.ClothesList" class="form-select"></select>
                            <option disabled selected>-----select Category---</option>
                            <span asp-validation-for="@Model.NewDrops.ClothesID" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Sizes" class="form-label"></label>
                            <select asp-for="@Model.NewDrops.Sizes" asp-items="@Model.SizesList" class="form-select"></select>

                            <span asp-validation-for="@Model.NewDrops.Sizes" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Price" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Price" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.Price" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.Quantities" class="form-label"></label>
                            <input asp-for="@Model.NewDrops.Quantities" class="form-control" />
                            <span asp-validation-for="@Model.NewDrops.Quantities" class="text-danger"></span>
                        </div>
                    </div>

                 
                    <div class="col-md-4">
                        <div class="mb-3">
                            <label asp-for="@Model.NewDrops.ClotheImage" class="form-label"></label>
                            <input type="file" name="files" id="uploadBox" class="form-control" />

                        </div>
                    </div>

                    <div class="mb-3">
                        <a asp-area="Admin" asp-controller="NewDrops" asp-action="Index" class="btn btn-danger">Back</a>
                        <button type="submit" class="btn btn-warning">Update</button>
                    </div>
                </div>

            </form>
        </div>

        <div class="col-md-4">
            @if (Model.NewDrops.ClotheImage != null)
            {
                <img src="@Model.NewDrops.ClotheImage" width="100%" />
            }
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_validationScriptsPartial" />
}

FashoinPoint/Areas/Admin/Views/NewDrops/Index.cshtml
@model List<NewDrops>

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h2>NewDrops List</h2>
        </div>
        <div class="col-md-6 text-end">
            <a asp-area="Admin" asp-controller="NewDrops" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle-fill"></i> Crate</a>
        </div>
    </div>
    <hr />
    @if (Model.Count() > 0)
    {
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">Name</th>
                    <th class="text-center">Brand</th>
                    <th class="text-center">ClothesType</th>
                    <th class="text-center">Sizes</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantities</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.ClotheName</td>
                        <td class="text-center">@item.Brand.Name</td>
                        <td class="text-center" >@item.Clothes.Name</td>
                        <td class="text-center">@item.Sizes</td>
                        <td class="text-center">@item.Price</td>
                        <td class="text-center">@item.Quantities</td>
                        <td class="d-flex align-items-center justify-content-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-area="Admin" asp-controller="NewDrops" asp-action="Details" asp-route-id="@item.Id"
                                   class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Details">
                                    <i class="bi bi-info-circle"></i>
                                </a>
                                <a asp-area="Admin" asp-controller="NewDrops" asp-action="Edit" asp-route-id="@item.Id"
                                   class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                                <a asp-area="Admin" asp-controller="NewDrops" asp-action="Delete" asp-route-id="@item.Id"
                                   class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>

                }

            </tbody>
        </table>
    }
    else
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-uppercase text-warning pt-4">No Records to Show</h2>
                </div>
            </div>
        </div>
    }

</div>

@section Scripts {
    <script>
        $('.table').DataTable();
    </script>
}